---
version: "1"  # The schema version of this config file.

ignore:  # A list of paths or files which Sourcery will ignore.
  - ansible_collections
  - ansible_roles
  - ansible_zengenti/mitogen-*
  - base-images
  - env
  - .env
  - .git
  - __init__.py
  - labs
  - pod
  - shit*.*
  - venv
  - .venv
  - .vscode

rule_settings:
  enable:
    - default
    - gpsg
  disable: [dont-import-test-modules]  # A list of rule IDs Sourcery will never suggest.
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: "3.11"  # A string specifying the lowest Python version your project supports.

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false
