---
name: Build Docker Dev Image

on:

  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-docker-dev-image.yml'
      - 'Dockerfile'
      - 'requirements.dev.txt'
      - 'pyproject.toml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - name: Checkout the repo to depth of 2 so we can see what has changed (if needed).
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        submodules: false
        clean: true

    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set short git commit SHA
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

    - name: Build and Push Development Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        target: development
        push: true
        tags: |
          ghcr.io/nickilby/jim-bob-dev:latest
          ghcr.io/nickilby/jim-bob-dev:${{ env.COMMIT_SHORT_SHA }}
...
